<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>VumbaSoft.ErmanApp</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\VumbaSoft.ErmanApp.Domain\VumbaSoft.ErmanApp.Domain.csproj" />
    <ProjectReference Include="..\VumbaSoft.ErmanApp.TestBase\VumbaSoft.ErmanApp.TestBase.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
  </ItemGroup>

</Project>
