<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>VumbaSoft.ErmanApp</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\VumbaSoft.ErmanApp.Domain\VumbaSoft.ErmanApp.Domain.csproj" />
    <ProjectReference Include="..\VumbaSoft.ErmanApp.Application.Contracts\VumbaSoft.ErmanApp.Application.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Volo.Abp.PermissionManagement.Application" Version="10.5.0" />
    <PackageReference Include="Volo.Abp.FeatureManagement.Application" Version="10.5.0" />
    <PackageReference Include="Volo.Abp.SettingManagement.Application" Version="10.5.0" />
    <PackageReference Include="Volo.Abp.Account.Application" Version="10.5.0" />
    <PackageReference Include="Volo.Abp.Identity.Application" Version="10.5.0" />
    <PackageReference Include="Volo.Abp.TenantManagement.Application" Version="10.5.0" />
    <PackageReference Include="MiniExcel" Version="1.41.4" />
  </ItemGroup>

</Project>
